dofile_once("mods/aim_assist/files/scripts/lib/tactic.lua")

Player = Entity{
    controls = ComponentField("ControlsComponent"),
    shooter = ComponentField("PlatformShooterPlayerComponent"),
    listener = ComponentField("AudioListenerComponent"),
    gui = ComponentField("InventoryGuiComponent"),
    wallet = ComponentField("WalletComponent"),
    pickupper = ComponentField("ItemPickUpperComponent"),
    hitbox = ComponentField("HitboxComponent", EntityGetFirstComponent),
    damage_model = ComponentField("DamageModelComponent"),
    genome = ComponentField("GenomeDataComponent"),
    ingestion = ComponentField("IngestionComponent"),
    alive = ComponentField("StreamingKeepAliveComponent", EntityGetFirstComponent),
    log = ComponentField("GameLogComponent"),
    sprite = ComponentField("SpriteComponent", "character"),
    aiming_reticle = ComponentField("SpriteComponent", "aiming_reticle"),
    character_data = ComponentField("CharacterDataComponent"),
    collision = ComponentField("PlayerCollisionComponent"),
    inventory = ComponentField("Inventory2Component"),
    autoaim = ComponentField{"LuaComponent", "iota_multiplayer.autoaim", _tags = "iota_multiplayer.autoaim", _enabled = false, script_shot = "mods/iota_multiplayer/files/scripts/perks/autoaim_shot.lua"},
    index = VariableField("iota_multiplayer.index", "value_int"),
    previous_money = VariableField("iota_multiplayer.previous_money", "value_int"),
    damage_frame = VariableField("iota_multiplayer.damage_frame", "value_int"),
    damage_message = VariableField("iota_multiplayer.damage_message", "value_string"),
    damage_responsible = VariableField("iota_multiplayer.damage_responsible", "value_string"),
    load_frame = VariableField("iota_multiplayer.load_frame", "value_int"),
    ingestion_data = VariableField("iota_multiplayer.ingestion_data", "value_string"),
}
