name: "Upload to Workshop"

on:
  push:
    tags:
      - "v*"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Extract tag annotation
        id: tag
        run: |
          MESSAGE=$(git tag -l --format='%(contents)' "${{ github.ref_name }}")
          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo "$MESSAGE" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 881100
          publishedFileID: 3694371849
          changelog: ${{ steps.tag.outputs.changelog }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
